#!/usr/bin/env bash
# file transfer given filepath, ip of server, user name of scp
# path to ssh private key that scp uses

if [ $# -lt 4 ]; then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit 1
fi

source_file=$1
host=$2
username=$3
identityFile=$4

scp -o StrictHostKeyChecking=no  -i "$identityFile"  "$source_file"  "${username}"@"${host}":~/
