#!/usr/bin/env bash
# login into the server
#ssh ubuntu@myserver
# install nginx
if ! command -v nginx> /dev/null; then
	echo  "Command not found! Installing nginx"
	sudo apt-get -y install nginx
fi
# configure Nginx to listen to port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
# change default page
echo Hello World!> /var/www/html/index.html
