#!/usr/bin/env bash
# login into the server
#ssh ubuntu@myserver
# install nginx
sudo apt -y install nginx

# change default page
echo Hello World!> /var/www/html/index.html
sudo /etc/init.d/nginx reload
