#!/usr/bin/env bash
# login into the server
#ssh ubuntu@myserver
# install nginx
if ! command -v nginx> /dev/null; then
	echo  "Command not found! Installing nginx"
	sudo apt-get -y install nginx
fi
# change default page
echo Hello World!> /var/www/html/index.html
sudo /etc/init.d/nginx restart
