#!/usr/bin/env bash
# install nginx

if ! command -v nginx> /dev/null; then
	        echo  "Command not found! Installing nginx"
		        sudo apt-get -y install nginx
fi

# configure Nginx to li llsten to por
sudo sed -i '/^\tlocation \/ {$/a \\n\tlocation \/redirect_me {\n\t\treturn 301 http:\/\/havugimana.tech/hello;\n\t}' /etc/nginx/sites-available/default
# change default page
