#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          manage_my_process
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Description:       Start  manage_my_process to allow run  and provide easy run enviroment
### END INIT INFO

case "${1:-''}" in
  'start')
          ./manage_my_process &
	  mypid="$(pidof -s -c "bash")"
	 echo "$mypid" > /var/run/my_process.pid
	 echo "manage_my_process started"
	 ;;
  
     'stop')
	     trap  "echo manage_my_process stopped"  SIGTERM
	    pkill -15 -f  manage_my_process
	    rm  -f "/var/run/my_process.pid"
	    ;;

    'restart')
	    trap  ""  SIGTERM
	    pkill -f manage_my_process
	    rm -f "/var/run/my_process.pid"
	    ./manage_my_process &
	    mypid="$(pidof -s -c "bash")"
	    echo "$mypid" > /var/run/my_process.pid 
	    echo "manage_my_process restarted"
	   ;;
   
   	*)
		echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
