#!/usr/bin/env bash
# The script stops "4-to_infinity_and_beyond" if running by using kill

#find the pid
pid_to_kill=$(pgrep -f "4-to_infinity_and_beyond")
for id in $pid_to_kill
do
if [ -z "$pid_t _kill" ]
then 
exit 
else
echo "$id"
kill "$id"
fi
done
