#!/usr/bin/env bash
# Bash script that displays 
  # Content of current dir
  # In a list format
   # Where only the parrt of the name after dash is display (example was given as  a ref)

n="$(wc -l </etc/passwd)"
i=1
while  [ "$i" -le "$n" ];
do
	line=$(head -$i < /etc/passwd |tail -1)
	a=$(echo "$line"| cut -d : -f1)
	b=$(echo "$line"| cut -d : -f3)
	c=$(echo "$line"|cut -d : -f6)
	echo -n "$a"
	echo -n ":$b:$c"
	echo 
	i=$((i+1))
done
