#!/usr/bin/env bash
# Bash script that displays 
  # Content of current dir
  # In a list format
   # Where only the parrt of the name after dash is display (example was given as  a ref)

   LIST="$(cat /etc/passwd)"
for  i  in $LIST;
do
	a=$(echo "$i"| cut -d : -f1)
	b=$(echo "$i"| cut -d : -f3)
	c=$(echo "$i"|cut -d : -f7-)
	echo -n "$a"
	echo -n ":$b:$c"
	echo 
done
