#!/usr/bin/env bash
# Bash script that displays with explanation
  # Content of current dir
  # In a list format
   # Where only the parrt of the name after dash is display (example was given as  a ref)

n="$(wc -l </etc/passwd)"
i=1
while  [ "$i" -le "$n" ];
do
	line=$(head -$i < /etc/passwd |tail -1)
	username=$(echo "$line"| cut -d : -f1)
	password=$(echo "$line"| cut -d : -f2)
	_UID=$(echo "$line" | cut -d : -f3)
	_GUID=$(echo "$line" | cut -d : -f4)
	userIDinfo=$(echo "$line" | cut -d : -f5)
	homedir=$(echo "$line" | cut -d : -f6)
	cmd=$(echo "$line" | cut -d : -f7)
	echo  "The user $username is part of the $_GUID gang, lives in $homedir and rides $cmd. $_UID's place is protected by the passcode $password, more info about the user here: $userIDinfo"
	i=$((i+1))
done
