#!/usr/bin/env bash
# Display "Best School" 10 times, But for the ninth iteration displays "Best School" and then "Hi"
i="1"

while [ "$i" -le "10" ];
do
if [ "$i" -eq "9" ]
then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
: $(( i++ ))
done
