#!/usr/bin/env bash
# Set up firewall. allowing incoming on 22, 443 and port 80 only
sudo apt install update
sudo apt install ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
echo y|sudo ufw enable
