#!/usr/bin/env bash
# running docker id and change restart apache2
if ! command -v apache2 > /dev/null; then
       echo  "Command not found! Installing apache2"
       sudo apt-get -y install apache2
fi
sudo chmod 644 /var/www/html/index.html
echo "Hello Holberton" > /var/www/html/index.html
sudo service apache2 restart
