#!/usr/bin/env bash
#running docker id and change restart apache2o
name="$(docker ps --format '{{.ID}}' --filter 'status=running')"
docker exec "$name" chmod 644 /var/www/html/index.html
docker exec "$name" echo "Hello Holberton" > /var/www/html/index.html
docker exec "$name" service apache2 start
